<a href="https://colab.research.google.com/github/sajid-sarker/CSE220-Lab/blob/main/Lab3_Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
def print_result(flag,a,b):
  print("The sum of the each row:",a)
  print("The sum of the each column:",b)
  print("_________________________")
  if flag:
    print("****valid******")
  else:
    print("****invalid******")
  print("_________________________")

def Balance(arr):
  row, col = arr.shape

  row_sum= np.array([0]*row)#initialize your own numpy array
  col_sum= np.array([0]*col)#initialize on your own numpy array
  flag = True ## Denote True as balanced and False for unbalanced

  for r in range(row):
    sum = 0
    for c in range(col):
      sum += arr[r][c]
    row_sum[r] = sum

  for c in range(col):
    sum = 0
    for r in range(row):
      sum += arr[r][c]
    col_sum[c] = sum

  for i in range(row):
    if row_sum[i] != col_sum[i]:
      flag = False
      break

  ##your code

  return flag,row_sum,col_sum




###DRIVER CODE
##TEST1
arr= np.array([[3,-9,7,0],
              [3,7,-1,6],
              [4,19,2,0],
              [0,7,-3,4]])
print("TEST CASE 1:", arr,sep="\n")
output_boolean,row_sum,col_sum = Balance(arr)
print_result(output_boolean,row_sum,col_sum)

##TEST2
arr= np.array([[1,2,7,0],
               [3,5,2,6],
               [4,2,0,0],
               [2,7,-3,4]])

print("TEST CASE 2:", arr,sep="\n")
output_boolean,row_sum,col_sum = Balance(arr)
print_result(output_boolean,row_sum,col_sum)

##TEST3
arr= np.array([[3,2,7,0],
               [3,7,2,6],
               [4,2,2,0],
              [2,7,-3,6]])
print("TEST CASE 3:", arr,sep="\n")
output_boolean,row_sum,col_sum = Balance(arr)
print_result(output_boolean,row_sum,col_sum)

TEST CASE 1:
[[ 3 -9  7  0]
 [ 3  7 -1  6]
 [ 4 19  2  0]
 [ 0  7 -3  4]]
The sum of the each row: [ 1 15 25  8]
The sum of the each column: [10 24  5 10]
_________________________
****invalid******
_________________________
TEST CASE 2:
[[ 1  2  7  0]
 [ 3  5  2  6]
 [ 4  2  0  0]
 [ 2  7 -3  4]]
The sum of the each row: [10 16  6 10]
The sum of the each column: [10 16  6 10]
_________________________
****valid******
_________________________
TEST CASE 3:
[[ 3  2  7  0]
 [ 3  7  2  6]
 [ 4  2  2  0]
 [ 2  7 -3  6]]
The sum of the each row: [12 18  8 12]
The sum of the each column: [12 18  8 12]
_________________________
****valid******
_________________________
